version: '3'

services:
  organizations_database:
    container_name: organizations_database
    user: root
    restart: always
    user: root
    restart: always
    image: postgres:10.6
    environment:
      POSTGRES_USER: dbz
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: organizations
    volumes:
      - ./dump:/docker-entrypoint-initdb.d  
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"  
    ports:
      - "5433:5432"