spring:
  datasource:
    url: jdbc:mysql://localhost:3308/persons
    username: root
    password: root

persons:
  datasource:
    host: localhost
    port: 3309
    database: persons
    username: root
    password: root