version: '3'

services:
  organizations_database:
    container_name: organizations_database
    user: root
    restart: always
    user: root
    restart: always
    image: postgres:10.6
    environment:
      POSTGRES_USER: dbz
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: organizations
    volumes:
      - ./organizations_pg_init.sql:/docker-entrypoint-initdb.d/organizations_pg_init.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"  
    ports:
      - "5433:5432"
  
  employees_database:
    container_name: employees_database
    user: root
    restart: always
    user: root
    restart: always
    image: postgres:10.6
    environment:
      POSTGRES_USER: dbz
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: employees
    volumes:
      - ./employees_pg_init.sql:/docker-entrypoint-initdb.d/employees_pg_init.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"  
    ports:
      - "5434:5432"
  zookeeper:
    image: debezium/zookeeper:1.6
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.6
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  connect:
    image: debezium/connect-jdbc:1.6
    build:
      context: debezium-jdbc
    ports:
     - 8083:8083
    links:
     - kafka
     - organizations_database
     - employees_database
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses